### ISSUE TITLE
Main Player Character

### ISSUE THREAD

**Issue by trevorkosht** [Collaborative-Software-Development-Club/Fall-2024-Unity-Game#1]
The character should be able to walk in cardinal directions.

 Using WASD and the arrow keys should move the character at a slow speed. 

Have speed be an easily changeable variable

sprite should be rendered in the direction of movement.

sprite art can be temporary, or the fox in the discord.

no animations required

collision detection with wall

**Comment by XBY015** [comment]
I've finished the moving with WASD and a running button, but I'm not sure if the branch "origin/Caleb-S" is the correct branch to upload progresses of the moving character. But I've uploaded the script to move a character to the branch "camera" because the camera need to have the player to be moved to follow
